caveman2cosmos/Caveman2Cosmos

- Sources/CvStructs.cpp
There are various issues in the save read and write code see https://github.com/caveman2cosmos/Caveman2Cosmos/commit/990107b7d35ea768e06855e8f47a4ed32b9b35a6 for a example.
> Save compatiblity fixes

- Sources/CvCityAI.cpp
Unused variable bHasBonusImprovement replaced with what I think was its intended function.
A few minor tweaks inside the function.
> AI_getImprovementValue

- Sources/CvCityAI.cpp
- Sources/CvPlayerAI.cpp
- Sources/CvUnitAI.cpp
> unitValueAI

- Assets/XML/Text/Units_CIV4GameText.xml
- Assets/XML/Units/CIV4UnitClassInfos.xml
- Assets/XML/Units/CIV4UnitInfos.xml
This is one of the ways we could re-balance this unit, probably the simplest one.
> Rebalance arsonist

- Assets/Python/Contrib/CvStrategyOverlay.py
It was reintroduced with python fixes branch merge.
> Fixed python bug

- Assets/XML/Events/CIV4EventInfos.xml
- Assets/XML/Events/CIV4EventTriggerInfos.xml
- Assets/XML/Text/Events_CIV4GameText.xml
This reverts commit 0b7ef5735b6fe28086a241c423cbf1e303915139.
> Revert "Removed a nonsense event, "cake flour"."

- Assets/XML/Events/CIV4EventTriggerInfos.xml
Now it shouldn't trigger anymore
> Deactivated nonsensical event

- Assets/XML/Technologies/CIV4TechInfos.xml
- Assets/XML/Text/Tech_CIV4GameText.xml
Specifically, "Hunting Tactics" requires "Hunting". Also fixed a teensie typo for another tech quote.
> fix(tech prereq): Hunting now requires Tracking

- Sources/CvGlobals.cpp
- Sources/CvGlobals.h
- Sources/CvXMLLoadUtility.h
- Sources/CvXMLLoadUtilitySet.cpp
- Sources/CyGlobalContext.cpp
- Sources/CyGlobalContext.h
- Sources/CyGlobalContextInterface4.cpp
- It's looking for xml files in a folder named "Python Config".
- Is not used in the dll or python.
> Removed CvPythonModulesInfo.

- Sources/CvGame.cpp
- Sources/CvGame.h
- Sources/CyGame.cpp
- Sources/CyGame.h
- Sources/CyGameInterface.cpp
Civ buildings and units stuff.
Not used in python.
> Removed 2 unused mothods.

- Sources/CvGlobals.cpp
- Sources/CvGlobals.h
- Sources/CvMap.cpp
- Sources/CvXMLLoadUtility.cpp
- Sources/CvXMLLoadUtilitySet.cpp
- Sources/CyGlobalContext.cpp
and removed the public functions in CvGlobals.
> Made CvXMLLoadUtility access info replacements members directly

- Sources/CvBuildingInfo.cpp
> Prereq building fix

- Assets/XML/Terrain/CIV4ImprovementInfos.xml
- Assets/XML/Text/Improvements_CIV4GameText.xml
- Sources/CvCity.cpp
- Sources/CvCity.h
- Sources/CvCityAI.cpp
- Sources/CvCityAI.h
- Sources/CvDLLButtonPopup.cpp
- Sources/CvGame.cpp
- Sources/CvGameInterface.cpp
- Sources/CvGameTextMgr.cpp
- Sources/CvMap.cpp
- Sources/CvPlayer.cpp
- Sources/CvPlayerAI.cpp
- Sources/CvPlot.cpp
- Sources/CvPlot.h
- Sources/CvTeam.cpp
- Sources/CvUnit.h
Something for raxo to try and TB to look at, and for any to comment on.
> Initial revised version of improvement upgrade code.

- Sources/CvCity.cpp
- Sources/CvCity.h
- Sources/CvCityAI.cpp
- Sources/CvPlayer.cpp
- Sources/CvPlot.h
- Sources/CvTeamAI.cpp
- Sources/CvUnitAI.cpp
Needs to be tested.
At the moment it is only used in `CvCity::calculateFeatureHealthPercentChange`
@MattOttawa 
Maybe you could implement this Iterator at other places as well.
> City Plot Iterator

- Assets/Python/Platyping/NaturalWonders.py
self.addSuitableCity doesn't seem to exist, so I'm guessin it never gets past:
if iBuilding == -1: continue
#551
#548
> Fixed python assert

- Sources/CvBuildingInfo.cpp
- Sources/CvInfos.h
I think I need to add a part to set arrays to NULL if pClassInfo's array is NULL and the Info running the func is not and bForceOverwrite is true.
> Fixed mistake I made while removing BuildingClass

- Sources/CvUnitInfo.cpp
> Fixed some issues with the bForceOverwrite tag on units

- Sources/CvBuildingInfo.cpp
- Sources/CvInfoWater.cpp
- Sources/CvInfoWater.h
- Sources/CvInfos.cpp
- Sources/CvInfos.h
- Sources/CvTalkingHeadMessage.cpp
- Sources/CvTalkingHeadMessage.h
- Sources/CyInfoInterface1.cpp
- Sources/CyInfoInterface2.cpp
Modders skipped the set functions.  These seem to be bts.
> Removed set functions from CvInfos that arn't called by other classes.

- Sources/CvGameCoreUtils.cpp
- Sources/CvGameCoreUtils.h
- Sources/CvInfos.cpp
- Sources/CvPlayer.cpp
- Sources/CvPlayer.h
- Sources/CyCity.h
- Sources/CyGameCoreUtils.cpp
- Sources/CyGameCoreUtils.h
- Sources/CyGameCoreUtilsInterface.cpp
- Sources/CyPlot.h
> Got rid of a couple python wrapper functions in CyGameUtils that are not doing anything.

- Sources/CvGameCoreDLL.h
- Sources/CvPlayer.cpp
- Sources/CvPlayerAI.cpp
- Sources/CvSelectionGroup.cpp
players can research without any cities and founding cities require tech
> 2 things for nomadic start

- Sources/CvPlot.cpp
Written in 10 minutes, not tested, may need other eyes, and opinions, on this before merging.
> Overflow protection for player plot culture values.

- Sources/CvCity.cpp
https://forums.civfanatics.com/threads/food-waste-at-hight-surplus.645946/
> Switched MAX_SURPLASS from 2000 to 200.

- Assets/XML/Units/Subdue_Animals_CIV4UnitInfos.xml
Desert tarantula was missing the ability to create bug - story and bug - stories that jungle tarantula had.
> fix(Animal): Give desert tarantula the ability to make same stories as jungle tarantula

- Assets/XML/Terrain/CIV4BonusInfos.xml
- Assets/XML/Terrain/CIV4FeatureInfos.xml
- Assets/XML/Terrain/CIV4ImprovementInfos.xml
- Assets/XML/Text/Improvements_CIV4GameText.xml
- PrivateMaps/C2C_World.py
More resources can be spawned on lake tiles in all mapscripts, and additional changes & control for lake generation c2c_world mapscript.
Some cleaning of naval improvement valid terrain types as well.
> Adjustments to lake generation and functionality

- Assets/Python/EntryPoints/CvRandomEventInterface.py
- Assets/XML/Text/Events_CIV4GameText.xml
I don't know what to do about the now broken translations.
> Changed text for dormant volcano event.

- Assets/Modules/My_Mods (unloaded)/Sacred_Sites/SacredSites_CIV4ImprovementInfos.xml
- Assets/Modules/My_Mods/Extinction/Extinction_CIV4BonusClassInfos.xml
- Assets/Modules/My_Mods/Extinction/Extinction_CIV4BonusInfos.xml
- Assets/Modules/Pepper2000/P2K_CIV4BonusInfos.xml
- Assets/Modules/Pepper2000/P2K_CIV4ImprovementInfos.xml
- Assets/XML/Schema/C2C_CIV4TerrainSchema.xml
- Assets/XML/Terrain/CIV4BonusClassInfos.xml
- Assets/XML/Terrain/CIV4BonusInfos.xml
- Assets/XML/Terrain/CIV4ImprovementInfos.xml
- Sources/CvInfos.cpp
Ongoing discussion:
https://forums.civfanatics.com/threads/ancient-era-wooden-watchtowers.663349/page-3#post-15926192
> fix(fortification spacing): fort predecessors properly inherit range of successors

- Assets/Python/BUG/PlayerUtil.py
- Assets/Python/Contrib/autologEventManager.py
- Assets/Python/CvMapGeneratorUtil.py
- Assets/Python/EntryPoints/CvRandomEventInterface.py
- Assets/XML/Schema/C2C_CIV4TerrainSchema.xml
- Assets/XML/Terrain/CIV4TerrainInfos.xml
- Assets/XML/Terrain/CIV4YieldInfos.xml
- Assets/XML/Text/Concepts_CIV4GameText.xml
- Assets/XML/Text/Improvements_CIV4GameText.xml
- Assets/XML/Text/Terrain_CIV4GameText.xml
- PrivateMaps/C2C_Donut.py
- PrivateMaps/C2C_PerfectMongoose_v310.py
- PrivateMaps/C2C_PerfectWorld2f.py
- PrivateMaps/C2C_SmartMap.py
- PrivateMaps/C2C_World.py
- Sources/CvArea.cpp
- Sources/CvGameTextMgr.cpp
- Sources/CvInfos.cpp
- Sources/CvInfos.h
- Sources/CvPlot.cpp
- Sources/CvPlot.h
XML tag added; bFreshWaterTerrain, but needs linking to isFreshWater().
Something like
`return algo::any_of(rect(getX(), getY(), 1, 1), GC.getTerrainInfo(getTerrainType()).isFreshWaterTerrain());`
should work, but the syntax is slightly wrong and can't figure out the type requirement algo::any_of is asking for 😅 
Also included (accidentally 🤦) is a hackish fix for the harbor bug; nuked lakes spawning if immediately merging, since the edge cases to check/update are actually somewhat annoying.
> Lake tweaks

- Sources/CvGame.cpp
- Sources/CvInfos.cpp
- Sources/CvInfos.h
> commented out CvImprovementInfo::setHighestCost

- Assets/Python/CvAdvisorUtils.py
- Assets/Python/CvDiplomacy.py
- Assets/Python/CvEventManager.py
- Assets/Python/EntryPoints/CvOptionsScreenCallbackInterface.py
- Assets/Python/EntryPoints/CvRandomEventInterface.py
- Assets/Python/OrionsMods/Immigration/Immigration.py
- Assets/Python/Screens/CvDomesticAdvisor.py
- Assets/Python/Screens/CvEspionageAdvisor.py
- Assets/Python/Screens/CvFinanceAdvisor.py
- Assets/Python/Screens/CvForeignAdvisor.py
- Assets/Python/Screens/CvMainInterface.py
- Assets/Python/Screens/CvVictoryScreen.py
- Assets/Python/Screens/RevolutionWatchAdvisor.py
- Assets/Python/Screens/Worldbuilder/WBBuildingScreen.py
- Assets/Python/Screens/Worldbuilder/WBCityDataScreen.py
- Assets/Python/Screens/Worldbuilder/WBCityEditScreen.py
- Assets/Python/Screens/Worldbuilder/WBCorporationScreen.py
- Assets/Python/Screens/Worldbuilder/WBEventScreen.py
- Assets/Python/Screens/Worldbuilder/WBGameDataScreen.py
- Assets/Python/Screens/Worldbuilder/WBInfoScreen.py
- Assets/Python/Screens/Worldbuilder/WBPlayerUnits.py
- Assets/Python/Screens/Worldbuilder/WBReligionScreen.py
- Sources/CyPlayer.cpp
- Sources/CyPlayer.h
- Sources/CyPlayerInterface3.cpp
The function I added to CyPlayer is interesting but might be slower. Gonna have to check.
> switched while loops to for loops for cities in python

- Assets/Python/Contrib/ParallelMaps.py
- Assets/XML/ParallelMaps_GlobalDefines.xml
- Sources/CvGame.cpp
- Sources/CvGame.h
- Sources/CvGameCoreDLL.h
- Sources/CvGlobals.cpp
- Sources/CvPlayer.cpp
- Sources/CvPlayer.h
- Sources/CvPlayerAI.cpp
- Sources/CvPlot.cpp
- Sources/CyGlobalContext.cpp
- Sources/CyPlayer.cpp
- Sources/CyPlayer.h
- Sources/CyPlayerInterface1.cpp
This is good enough for me actually.
> deleted ifdef parallel maps

- Assets/Modules/Alt_Timelines/Megafauna_Units/Mammoths/Mammoths_CIV4UnitInfos.xml
- Assets/Modules/Alt_Timelines/Steampunk/Steampunk_CIV4UnitInfos.xml
- Assets/Modules/Custom_Religions/Voodoo/Voodoo_CIV4UnitInfos.xml
- Assets/Modules/Thunderbrd/Traits/C2C_TB_CIV4TraitInfos.xml
- Assets/Python/Contrib/Pedia/PediaFeature.py
- Assets/XML/Terrain/CIV4ImprovementInfos.xml
- Assets/XML/Units/CIV4BuildInfos.xml
- Assets/XML/Units/CIV4UnitInfos.xml
- Assets/XML/Units/CulturalUnits_CIV4UnitInfos.xml
- Sources/CvPlot.cpp
- Sources/CvPlot.h
Towers affected by traits, can be built at higher levels with tech, have better normalized build time, and have linked 2D build buttons.
- Still needs to fix the issue with cultural borders disappearing on upgrading
- Steel Watchtower needs new 3D art, currently duplicates Stone Watchtower
> fix(tower improvements): Misc issues

- Sources/CvArtFileMgr.h
- Sources/CvBuildingInfo.h
- Sources/CvCity.h
- Sources/CvEnums.h
- Sources/CvFractal.h
- Sources/CvGame.h
- Sources/CvGameCoreUtils.h
- Sources/CvInfos.h
- Sources/CvMap.h
- Sources/CvMapExternal.h
- Sources/CvMapGenerator.h
- Sources/CvMapInterfaceBase.h
- Sources/CvPlayer.h
- Sources/CvPopupReturn.h
- Sources/CvSelectionGroup.h
- Sources/CvStructs.h
- Sources/CvTeam.h
- Sources/CvUnit.h
- Sources/CvViewport.h
- Sources/CyTeam.h
They arn't correct after I removed unused functions from interface.
> deleted Exposed to Python comments

- Assets/Python/EntryPoints/CvRandomEventInterface.py
can cause bug in fire even maybe.
> changed var names

- Sources/CvInfos.cpp
- Sources/CvInfos.h
- Sources/CvPlayer.cpp
- Sources/CvXMLLoadUtility.h
- Sources/CvXMLLoadUtilityModTools.cpp
- Sources/CvXMLLoadUtilityModTools.h
This reverts commit fe77686713af11662e3fb2160aceafb898aa3c41.
> Revert "switched some copy non defaults code (#796)"

- .github/workflows/commit.yml
- Test/Python3/pytest.ini
- Test/Python3/requirements.txt
- Test/Python3/setup.sh
- Tools/XMLTools/BlazeScripts/Common.py
- Tools/XMLTools/BlazeScripts/OrganizeTechAudios.py
- Tools/XMLTools/BlazeScripts/PrintSortedWorkerBuildList.py
- Tools/XMLTools/BlazeScripts/test/test_Common.py
This PR consists of 3 commits:
One refactors out a common function duplicated in two files.
One adds a very basic unit test framework.
And the last one adds a test for the duplicated function, just as an illustration of how to add tests.
I do not have in-depth knowledge about in what data is to be expected to be read from these functions, so the tests can definitely be improved.
To add a new test you can simply create a test directory in the appropriate place, ensure that you can import the module you want to test (usually by adding `__init__.py` so the modules becomes importable), and then create a file `test_*.py` that contains something like this:
```python
def test_something() -> None:
assert int(1) == int(float(1))
def test_something_else() -> None:
assert str(3) = "3"
assert "yolo" …
```
> Python unit test

- Assets/Modules/Pepper2000/P2K_CIV4BonusInfos.xml
- PrivateMaps/Desert Planet fixed.CivBeyondSwordWBSave
- PrivateMaps/GEM - ROM 2.7 - 5 civs - Legacy.CivBeyondSwordWBSave
- PrivateMaps/LEM - Harrier - 10 Civs.CivBeyondSwordWBSave
- PrivateMaps/LEM - Harrier - 21 Civs.CivBeyondSwordWBSave
- PrivateMaps/LEM - Harrier - Raw.CivBeyondSwordWBSave
- PrivateMaps/SEM - Harrier - 20 Civs.CivBeyondSwordWBSave
- PrivateMaps/SEM - Harrier - 9 Civs.CivBeyondSwordWBSave
- PrivateMaps/SEM - Harrier - Raw.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Duel World.CivBeyondSwordWBSave
- PrivateMaps/Space Map - ItSmallWorld.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Large01_V3.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Large02_V3.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Large03_V3.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Large04_V3.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Large05_V3.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard01_V9.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard02_V7.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard03_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard04_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard05_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard06_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard07_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard08_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard09_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard10_V6.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Snofru Standard11_V5.CivBeyondSwordWBSave
- PrivateMaps/Space Map - Standard_Solar_System_v10.CivBeyondSwordWBSave
- PrivateMaps/StrategyOnly's Land_Testing C2C_Narnia 17 st 69X59.CivBeyondSwordWBSave
- PrivateMaps/StrategyOnly.CivBeyondSwordWBSave
Space resources now are available in WB.
All scenarios now have resources generating randomly on start.
> Resource generation tweaks on scenarios

- Sources/CvCityAI.cpp
- Sources/CvGame.cpp
- Sources/CvGameInterface.cpp
- Sources/CvMap.cpp
- Sources/CvMapInterfaceBase.h
- Sources/CvPlayer.cpp
- Sources/CvPlayerAI.cpp
- Sources/CvPlayerAI.h
- Sources/CvPlot.cpp
- Sources/CvPlot.h
- Sources/CvSelectionGroup.cpp
- Sources/CvUnit.cpp
- Sources/CvUnitAI.cpp
- Sources/CvViewport.cpp
- Sources/CvViewport.h
- Sources/CyMap.cpp
- Sources/CyMap.h
- Sources/CyMapInterface.cpp
> deleted static from CvPlot::rect

- Sources/CvCityAI.cpp
small fix so evaluation actually evaluates bonus on plot
> add bonustype to plotinfo

- Assets/Python/EntryPoints/CvCultureLinkInterface.py
- Assets/Python/EntryPoints/CvWBInterface.py
- PrivateMaps/C2C_PerfectMongoose_v310.py
- PrivateMaps/C2C_PerfectWorld2f.py
- PrivateMaps/C2C_Totestra.py
This reverts commit 15014d43889dcac5aa24a91b80a6d037852c32a8.
> Revert "deleted GetInfoType function (#981)"

- Sources/CvBuildingInfo.h
- Sources/CyInfoInterface1.cpp
- Sources/CyStructsInterface1.cpp
- Sources/IDValueMap.h
#953
Havn't tested yet. I'll leave that to raxxo.
Python should be:
for pair in GC.getBuildingInfo(0).getTechHappinessTypes():
[tab] iTech = pair.first
[tab] iValue = pair.second
> exposed TechHappinessTypes and TechHealthTypes to python

- Assets/Python/Python.pyproj
- Sources/C2C (VS2019).sln
For modifying python files with vs. Intellisense works.
I only use vs to compile though, so I'm not sure if it is useful to me.
This can be deleted later if nobody likes it much.
> added vs project file for python

- Sources/CvDllPythonEvents.cpp
> fixed assert from NULL CyUnit

- Assets/Python/EntryPoints/CvRandomEventInterface.py
- Assets/Python/Screens/CvVictoryScreen.py
also switched some getInfoTypeForString calls
> switched a unit loop in doVolcanoNeighbouringPlots()

- Sources/CvDLLPythonIFaceBase.h
- Sources/CvGameCoreDLL.h
- Sources/CvMapGenerator.cpp
- Sources/CvMapGenerator.h
- Sources/CyMapGenerator.cpp
- Sources/CyMapGenerator.h
- Sources/CyMessageControl.cpp
- Sources/CyMessageControl.h
- Sources/CyPlayer.cpp
- Sources/CyPlayer.h
Does this from the code cleanup project:
CvDLLPythonIFaceBase functions that return arrays, update to use vectors
Added by billw2012
> switched functions to a similar boost one

- Sources/CvDLLPython.cpp
- Sources/CyArea.cpp
- Sources/CyArea.h
- Sources/CyAreaInterface.cpp
- Sources/CyBoolExprInterface.cpp
- Sources/CyCity.cpp
- Sources/CyCity.h
- Sources/CyInfoInterface1.cpp
- Sources/CyInfoInterface2.cpp
- Sources/CyInfoInterface3.cpp
- Sources/CyInfoInterface4.cpp
- Sources/CyPropertiesInterface.cpp
- Sources/CySelectionGroup.cpp
- Sources/CySelectionGroup.h
- Sources/CySelectionGroupInterface.cpp
- Sources/CyStructsInterface1.cpp
- Sources/CyTeamInterface.cpp
- Sources/CyUnit.cpp
- Sources/CyUnit.h
no_init disables the use of __init__() in python for class.
> added no_init to some Cy classes

- Sources/CvCity.h
- Sources/CvCityAI.cpp
- Sources/CvCityAI.h
- Sources/CvDLLButtonPopup.cpp
- Sources/CvGameCoreDLL.h
Did this:
// Toffer - ToDo - Change iValue type to int64_t,
//	or reduce scoring as it gets dangerously close to overflowing as it is.
> scored building value long long

- Assets/XML/GameText/CIV4GameTextInfos_GreatPeople.xml
> fixed 3 typos in Great People Text

- .editorconfig
- Assets/Modules/Cultures/Cultures_Cultural_CIV4UnitInfos.xml
- Assets/XML/Terrain/CIV4ImprovementInfos.xml
- Sources/.editorconfig
- Sources/C2C (VS2019).vcxproj
- Sources/C2C (VS2019).vcxproj.filters
- Sources/CvCityAI.cpp
- Sources/CvOutcome.cpp
- Sources/CvPlayer.cpp
- Sources/CvSettlerAI.cpp
- Sources/CvSettlerAI.h
- Sources/CvUnitAI.cpp
- Sources/CvUnitAI.h
- Sources/CvValueService.cpp
- Sources/CvValueService.h
- Sources/CvWorkerAI.cpp
- Sources/CvWorkerAI.h
- Sources/GroupingParams.h
Modifications, and testing improvements to see if we can improve worker AI
AI still builds forts way too often, but cause of this issue has been identified.
> Worker tweaks and other refactor

- Assets/XML/GameText/CIV4GameTextInfos_GreatPeople.xml
Several spelling corrections in Great People text
> Several spelling corrections in Great People text

- Sources/CvCityAI.cpp
this reworks AI_newbestplotbuild (to be renamed to AI_bestplotbuild) again
the function specifically checks what is the best improvement and build to use for plots for a city, and only checks plots inside the city limit of that city.
> Rework best plot build again

- Sources/CyGlobalContext.cpp
- Sources/CyGlobalContext.h
- Sources/CyGlobalContextInterface4.cpp
python uses CyArtFileMgr to get art.
> deleted unused getArtInfo func from CyGlobalContext

- Sources/CvBuildingInfo.cpp
- Sources/CvImprovementInfo.cpp
- Sources/CvInfos.cpp
- Sources/CvInfos.h
getArtInfo() searches a map for a tag name. If tag is not found, then FAssert and return NULL.
These checks before getArtInfo() are not needed I think.
> deleted extra missing art checks.

- Assets/Modules/Cultures/Cultures_CIV4BuildInfos.xml
- Assets/Modules/zWIP/Sacred_Sites/SacredSites_CIV4BuildInfos.xml
- Assets/XML/Schema/C2C_CIV4UnitSchema.xml
- Assets/XML/Units/CIV4BuildInfos.xml
- Sources/CvCityAI.cpp
- Sources/CvInfos.cpp
- Sources/CvInfos.h
- Sources/CvPlayer.cpp
- Sources/CvPlayer.h
- Sources/CvSelectionGroup.cpp
- Sources/CvUnit.cpp
- Sources/CvXMLLoadUtility.h
- Sources/CvXMLLoadUtilitySet.cpp
- Sources/CyPlayer.cpp
- Sources/CyPlayer.h
- Sources/CyPlayerInterface1.cpp
- Sources/CyUnit.cpp
- Sources/CyUnit.h
- Sources/CyUnitInterface1.cpp
Hope this simplification helps you (@flabbert) in your worker AI quest.
> Simplified ::canBuild(, got rid of bCanRemoveWithNoProductionGain tag from featureStructs

- Sources/CvInfos.cpp
- Sources/CvInfos.h
> deleted unused CvWorldInfo tag iNumFreeBuildingBonuses

- Sources/CvEnums.h
- Sources/CvGame.cpp
- Sources/CvGameTextMgr.cpp
- Sources/CvGlobals.cpp
- Sources/CvInitCore.cpp
- Sources/CvReplayInfo.cpp
- Sources/CvStructs.cpp
#define NUM_GAMEOPTION_TYPES GC.getNumGameOptionInfos()
> deleted NUM_GAMEOPTION_TYPES

- Sources/CvGameCoreDLL.def
- Sources/CvTeamAI.cpp
- Sources/CvTeamAI.h
This reverts commit 0703f4f5dea7198c2d7723d2fa16e7a87d2d2a6b.
> Revert "Restored a missing DllExport in CvTeamAI"

- Assets/XML/Buildings/GroupWonders_CIV4BuildingInfos.xml
- Assets/XML/Buildings/NationalWonders_CIV4BuildingInfos.xml
- Assets/XML/Buildings/zAnimals_CIV4BuildingInfos.xml
- Assets/XML/GameText/UnitHelp_CIV4GameText.xml
- Assets/XML/Misc/CIV4RouteInfos.xml
- Assets/XML/Terrain/CIV4FeatureInfos.xml
- Assets/XML/Terrain/CIV4ImprovementInfos.xml
- Assets/XML/Units/CIV4BuildInfos.xml
- Assets/XML/Units/CIV4UnitCombatInfos.xml
- Sources/CvGameTextMgr.cpp
- Sources/CvPlot.cpp
Pretty minor stuff, but enough to merge now if someone wants to take a quick look and confirm things look OK.
> Small fixes

- Assets/Python/EntryPoints/CvRandomEventInterface.py
- Assets/XML/Events/CIV4EventInfos.xml
- Assets/XML/Events/CIV4EventTriggerInfos.xml
- Assets/XML/GameText/Events_CIV4GameText.xml
Tested with a few hundred turns autoplay, but could use more playtesting to make sure there's no oddities. Merge with animal stockpile pr #1390 when that's ready, I guess.
> Volcano tweaks

- Assets/XML/GameText/IdeaClass_CIV4GameText.xml
Only text translation for Italian
> Italian translation

- Assets/XML/GameText/Bonus_CIV4GameText.xml
- Assets/XML/GameText/Buildings_Animals_CIV4GameText.xml
- Assets/XML/GameText/CIV4GameTextInfos_C2C.xml
- Assets/XML/GameText/Combat_CIV4GameText.xml
- Assets/XML/GameText/Global_CIV4GameText.xml
- Assets/XML/GameText/Hints_CIV4GameText.xml
- Assets/XML/GameText/Modules/Alt_Timelines/Megafauna/Megafauna_CIV4GameText.xml
- Assets/XML/GameText/Modules/Pepper2000/P2K_CIV4GameText.xml
- Assets/XML/GameText/Pedia_CIV4GameText.xml
- Assets/XML/GameText/Promotions_CIV4GameText.xml
- Assets/XML/GameText/Revolution_CIV4GameText.xml
- Assets/XML/GameText/Units_CIV4GameText.xml
> Ita translation

- Assets/XML/GameText/Build_CIV4GameText.xml
- Assets/XML/GameText/Combat_CIV4GameText.xml
- Assets/XML/GameText/Global_CIV4GameText.xml
- Assets/XML/GameText/Promotions_CIV4GameText.xml
- Assets/XML/GameText/UnitHelp_CIV4GameText.xml
- Assets/XML/GameText/Units_CIV4GameText.xml
As always, please let me know in case of problems. Thank you!
> Subcombat unit types and normal units (first part)

- Assets/XML/GameText/CIV4GameTextInfos_C2C.xml
- Assets/XML/GameText/Global_CIV4GameText.xml
- Assets/XML/GameText/Modules/Pepper2000/P2K_CIV4GameText.xml
- Assets/XML/GameText/Promotions_CIV4GameText.xml
- Assets/XML/GameText/Traits_CIV4GameText.xml
- Assets/XML/GameText/Units_CIV4GameText.xml
> Normal units (second part), main UI (first part), traits correction, etc

- Assets/XML/GameText/BUG_CIV4GameText.xml
- Assets/XML/GameText/Gameoptions_CIV4GameText.xml
- Assets/XML/GameText/Global_CIV4GameText.xml
- Assets/XML/GameText/Revolution_CIV4GameText.xml
- Assets/XML/GameText/Special/exeText.xml
- Assets/XML/GameText/Units_CIV4GameText.xml
> Main UI (second part) City Screen (first part)

- .github/workflows/commit.yml
Seems to be broken. It doesn't check anything important anyways.
> disabled python 3 unit test on commit

- Sources/CvPlayer.cpp
> Temp fix to workers not doing their job

- Assets/Python/EntryPoints/CvRandomEventInterface.py
- Assets/XML/Events/CIV4EventInfos.xml
- Assets/XML/Events/CIV4EventTriggerInfos.xml
- Assets/XML/GameText/Events_CIV4GameText.xml
All existing events have been looked into rebalanced, for game speed and to have some meaning and impact in the game.
No new events were added in this rework, I will be adding events 1 by 1 separately for testing purposes.
Some events got extra options.
> Total event rework.

- Assets/Modules/Thunderbrd/Traits/C2C_TB_CIV4TraitInfos.xml
Updated complex traits:
- Balance adjusted
- Weak traits were buffed
- Strong traits were nerfed
- Negative traits adjusted to not be so punishing
- Adjust traits to have more identity(picking a trait has some theme instead of just random stat changes) -> Like greed reduces gold
- Normal traits were not touched, only trait_1 were adjusted, 2,3,4 are left as they are,
> Complex trait update

- Assets/XML/Events/CIV4EventInfos.xml
- Assets/XML/Events/CIV4EventTriggerInfos.xml
Full revert to the event rework, since by testing I have concluded that it probably breaks save compatibility. I will do my own testing and once I resolve it, I will slowly release the event rework piecemeal
> Full revert to the event rewor

- Sources/CvGlobals.cpp
- Sources/CvGlobals.h
- Sources/CvMap.cpp
Savefiles with any initialized multimaps are literally unplayable without this fix
> Fix critical issue when loading multimap savefiles that pathfinding objects would not get assigned to the correct maps

- Assets/Modules/P2K_Multimaps_Test/MM_CIV4UnitInfos.xml
- Sources/CvMap.cpp
- Sources/CvMap.h
- Sources/CyMap.cpp
- Sources/CyMap.h
This also fixes the bug Matt noted in Discord
> Improve logic for determining coordinate of arriving units to a multimap

- Assets/XML/Buildings/SpecialBuildings_CIV4BuildingInfos.xml
- Assets/XML/Buildings/zAnimals_CIV4BuildingInfos.xml
- Sources/CvPlayer.cpp
realistic building cost option
> Prehistoric age, animal, and special buildings values adjusted

- Assets/XML/GameInfo/CIV4ProjectInfo.xml
> renaissance era

- Assets/XML/GameText/CIV4GameTextInfos_GreatPeople.xml
Archimedes' workshop, description of Yidzhak Mordechai, Hellenic Gymnasium.
> Minor typo fixes

- Assets/Modules/Alt_Timelines/Megafauna/Megafauna_CIV4BuildingInfos.xml
- Assets/XML/Events/CIV4EventInfos.xml
- Assets/XML/Events/CIV4EventTriggerInfos.xml
- Assets/XML/GameText/Events_CIV4GameText.xml
updated missing texts for events
updated event triggers and values
enabled big cats in prehistoric
> bugfix-patch

- Assets/XML/GameText/CIV4GameTextInfos_GreatPeople.xml
- Assets/XML/GameText/Events_CIV4GameText.xml
I forgot to explain in the commits that I changed Goodwill's surname because all sources call him "Zwelithini"; "kaBekhuzulu" is a sort of "son of XYZ" arrangement and unlike (say) Iceland doesn't routinely get used as one's surname.
> More typos for you

- Assets/XML/GameText/Global_CIV4GameText.xml
- PrivateMaps/C2C_Totestra.py
> added a text key for the Totestra map script description

- Assets/Python/Screens/Pedia/PediaLeader.py
- Assets/XML/GameText/Pedia_CIV4GameText.xml
> Added text key for the word personality in leaders pedia

- Assets/XML/GameText/Units_CIV4GameText.xml
Name of the hero in question is Luís Alves de Lima e Silva but the í was omitted on C2C. I've also mentioned his title Duke of Caxias on his wiki entry since besides the first phrase the entire entry calls him Caxias.
> Fixed typo on Brazilian Hero and clarified his title on wiki entry

- Assets/XML/Units/CIV4PromotionInfos.xml
Removed PROMOTION_RESCUE_DOG1 -- PROMOTION_COMBAT2 requirement since … dogs can't get PROMOTION_COMBAT2.
> Dog promotion bugfix

- Sources/CvUnitAI.cpp
- was using the wrong group (pGroup -> setGtoup) for the MOVE_TO mission order
- Added some logs at end of AImove method, to track if some units are'nt doing anything
> AI test attack city - Fix for Endless loop
