caveman2cosmos/Caveman2Cosmos

.gitignore
All `*.nif` files in the `Assets` directory should be ignored because they should be placed in `UnpackedArt` instead.
=> Ignore *.nif files in Assets

Sources/CvGameObject.cpp, Sources/CvGameObject.h, Sources/CvGlobals.cpp, Sources/CvGlobals.h, Sources/CvInfos.cpp, Sources/CvInfos.h, Sources/IDValueMap.h, Sources/IntExpr.cpp, Sources/IntExpr.h
I reverted some changes from svn10994 to fix IDValueMap and it's usages.
These changes broke the adaptValueToGame functionality including the city limit scaling by worldsize.
Fixes #63
=> Possible fix for city limit scaling by worldsize

Assets/Python/Contrib/Pedia/PediaBonus.py, Assets/Python/Contrib/Pedia/PediaBuilding.py, Assets/XML/Text/Pedia_CIV4GameText.xml, Assets/XML/Text/Promotions_CIV4GameText.xml
My first pull request. I keep it small, cause it's mainly a test, if I made everything right. 
Content: Some new translations for latitude and auto-build pedia labels and some minor corrections
- the history label should now display correctly
- German newline instead of paragraph to suppress hanging feeder (not used in German)
=> feat(Language): german translations to some of the new pedia labels

Assets/XML/Text/Units_CIV4GameText.xml
Sun and Brown bears had a pedia entry suggesting they construct bird buildings, not bear ones (their actual functionality was fine). Tiny change, mostly to see if I can figure out git kraken / how best to submit text fixes I find
=> fix(pedia): sun, brown bears entry no longer states they make bird buildings

Assets/Modules/Alt_Timelines/Megafauna_Units/Bear/Bear_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Bear/Bear_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Big_Cats/Big_Cats_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Big_Cats/Big_Cats_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Bison_Rider/BisonRider_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Bison_Rider/BisonTrainer_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/DeerRider/DeerRider_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/DeerRider/DeerRider_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Giraffe/Giraffe_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Mammoths/Mammoths_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Mammoths/Mammoths_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Rhinoceros/Rhinoceros_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Rhinoceros/Rhinoceros_CIV4UnitInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Rhinoceros/zDepend_Rhinoceros_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Zebra_Mounts/ZebraMounts_CIV4BuildingInfos.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Zebra_Mounts/ZebraMounts_CIV4GameText.xml, Assets/Modules/Alt_Timelines/Megafauna_Units/Zebra_Mounts/ZebraMounts_CIV4UnitInfos.xml, Assets/XML/Buildings/NationalWonders_CIV4BuildingInfos.xml
This should be it for matching the alternate history animal trainer wonders and units with each other (plus the log roller because it annoyed me once), though the entire animal trainer module really needs a polishing pass or two; it's all over the place, both in coding practices and pedia text
=> fix(wonder prereqs): mostly animal trainer+heritages and units, plus log roller

Assets/Modules/Alt_Timelines/Atompunk/Atompunk_CIV4TechInfos.xml, Assets/Modules/Alt_Timelines/Biopunk/Biopunk_CIV4TechInfos.xml, Assets/Modules/Alt_Timelines/Clockpunk/Clockpunk_CIV4TechInfos.xml, Assets/Modules/Alt_Timelines/Cyberpunk/Cyberpunk_CIV4TechInfos.xml, Assets/Modules/Alt_Timelines/Dieselpunk/Dieselpunk_CIV4TechInfos.xml, Assets/Modules/Alt_Timelines/Nanopunk/Nanopunk_CIV4TechInfos.xml, Assets/Modules/Alt_Timelines/Steampunk/Steampunk_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Andean/Andeanism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Asatru/Asatru_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Bahai/Bahai_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Canaanism/Canaanism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Caodai/CaoDai_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Druid/Druidism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Jainism/Jainism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Mesopotamian/Mesopotamism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Mormon/Mormon_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Ngai/Ngaiism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Rodnovery/Rodnovery_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Scientology/Scientology_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Shaman/Shamanism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Shinto/Shinto_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Sikh/Sikhism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Tengri/Tengriism_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Voodoo/Voodoo_CIV4TechInfos.xml, Assets/Modules/Custom_Religions/Yoruba/Yoruba_CIV4TechInfos.xml, Assets/XML/Technologies/CIV4TechInfos.xml, Assets/XML/Technologies/TechInfos_MP_Rename.py, Tools/XMLTools/TechInfos_MP_Rename.py
As Thunderbird suggested, multiplayer quote sfx are now either the "You have discovered X" from vanilla quotes where appropriate, or just the 'ding' sfx in place of potentially long, drawn out spoken quotes.
I initially wanted to rename all the tech .mp3 files to have a prefix matching the era the tech is in, for ease of editing them later (and also just for consistency's sake since they're all over the place...) but that didn't quite work out. So, guess I'm doing that manually now in a separate project as I'm passing through recording quotes (will make a different PR as I finish prehistoric era).
=> fix(audio): mp tech quotes now either vanilla mp quotes or just 'ding'

Assets/XML/BasicInfos/CIV4ANDConceptInfos.xml, Assets/XML/BasicInfos/CIV4DCMConceptInfos.xml, Sources/CvGame.cpp, Sources/CvGame.h, Sources/CvUnit.cpp
CvGame: Added const to methods.
CvGame: Moved function variable declarations. (let me know if that's too annoying)
CvGame: Reduced a loop's size from MAX_PLAYERS (51) to MAX_PC_PLAYERS (40) and removed if(!isNPC()).
CvGame: Removed if(iter != NO_PLAYER) from a loop that starts with 0.
CvUnit: Changed GC.getDefineINT("EVENT_MESSAGE_TIME") calls to GC.getEVENT_MESSAGE_TIME()
CvUnit: Removed a pointless function variable named bBitter from about 5 DCM airBomb methods.
- I don't think bBitter is an upcoming TB thing, but I can change this pull request if I'm wrong.
=> code cleanup

Assets/XML/Technologies/CIV4TechInfos.xml, Sources/CvGame.cpp, Sources/CvPlayer.cpp, Sources/CvPlayerAI.cpp, Sources/CvPlot.cpp, Sources/CvTeam.cpp
Changes make sense to me, though I would like a second opinion.
Was a bug in the AI code that add value of the mountaneering tech specifically by counting up all mountains inside a players culture, it only did this if usable mountain option was turned off, which is moot as the tech could not even be invented if that option was off.
Optimized away a couple loop through all techs in AI valuation of promotions and unit combat types related to mountaineering.
Streamlined what the option does when turned off:
1. Tech is now available even when the option is off. It unlocks improvements, buildings and promos that I see no reason to optionalize in any way.
2. Inventing the tech won't allow all owned units to pass mountains like how it is with the option on. 
3. Land units must have relevant …
=> Small clean up in the usable mountain GM code.

Assets/XML/Art/CIV4ArtDefines_Improvement.xml, Assets/XML/Schema/C2C_CIV4TerrainSchema.xml, Assets/XML/Terrain/CIV4ImprovementInfos.xml, Assets/XML/Text/Improvements_CIV4GameText.xml, Sources/CvCity.cpp, Sources/CvCityAI.cpp, Sources/CvGameTextMgr.cpp, Sources/CvInfos.cpp, Sources/CvInfos.h, Sources/CvPlayer.cpp, Sources/CvPlot.cpp, Sources/CvPlot.h, Sources/CvTeam.cpp, Sources/CvUnitAI.cpp
This should wait till after v40.1 is released, but I hope others will help me by reviewing the code or by testing it in game by turning on the resource depletion BUG option. 
Things to look for when testing which are not related to bonus depletion are  bonus discovery and improvement upgrading as that too was tweaked.
Bonuses can be discovered by culturally owned improvements even if not worked by the citizens of a city.
Mines will no longer perma-deplete, only bonuses may deplete with the resource depletion BUG-option.
Some improvement tags can be removed, but I didn't do this fearing it might break saves.
=> Rationalized bonus disc/depletion code for improvements

Sources/CvGlobals.cpp, Sources/CvGlobals.h
getCivPlayers() shouldn't be used in the dll or python anymore right?
I didn't change the values being sent to the exe. I know toffer just sorted this stuff out.
=> removed 3 get functions from CvGlobals.

Assets/Modules/Pepper2000/P2K_CIV4ImprovementInfos.xml, Assets/Modules/Pepper2000/P2K_CIV4UnitInfos.xml, Assets/Modules/Pepper2000/Pepper2000Terrain_CIV4GameText.xml, Assets/Modules/Pepper2000/Pepper2000_CIV4TerrainInfos.xml, Assets/XML/Art/CIV4ArtDefines_Terrain.xml, Assets/XML/Terrain/CIV4FeatureInfos.xml, Assets/XML/Terrain/CIV4ImprovementInfos.xml, Assets/XML/Terrain/CIV4TerrainInfos.xml, Assets/XML/Text/Terrain_CIV4GameText.xml, PrivateMaps/A Space Map - Duel World.CivBeyondSwordWBSave, PrivateMaps/A Space Map - ItSmallWorld.CivBeyondSwordWBSave, PrivateMaps/A Space Map - Large_Solar_System_v10.CivBeyondSwordWBSave, PrivateMaps/A Space Map - Tiny_Alternate_System_v5.CivBeyondSwordWBSave, PrivateMaps/A Space Map - VerticalSolar Cut.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Duel06_V1.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Duel07_V1.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Duel08_V1.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Duel09_V1.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard01_V6_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard02_V4_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard03_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard04_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard05_Raxo_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard06_Thunderbrd_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard07_Joseph_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard08_Snofru_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard09_Snofru_V3_SVN.CivBeyondSwordWBSave, PrivateMaps/A Space Map - _Standard10_Snofru_V3_SVN.CivBeyondSwordWBSave
I didn't notice it due to tag override.
Some space content is located in main mod - mars/moon + some other stuff.
Only saves started in space scenarios will be broken.
Space scenarios are affected, regular scenarios are fine.
=> Renamed TERRAIN_SPACE to TERRAIN_CISLUNAR_SPACE

Sources/CyGlobalContext.cpp
Id like to go a step further and get rid of the ability to hide asserts for getInfoTypeForString altogether.
It doesn't make sense to have references to xml types that don't exist.
=> Added back the assert for getInfoTypeForString calls that come from python

Sources/CvPlot.cpp
I added #ifdef to this so that there are no (intentional) changes to the dll from this.
=> fix crash when switching map

Sources/CvInfos.h
These default NULL values will cause crash if used (they're not used).
=> Removed the default NULL value for the copyNoneDefaults params.

Assets/XML/Units/Subdue_Animals_CIV4UnitInfos.xml, Assets/XML/Units/zDepend_Entertainer_Animals_CIV4UnitInfos.xml
irishhombre: It always irritated me that entertainers could not build all stories so I fixed it. While I was at I also fixed Paleolithic cats and marsupials. Paleolithic cats stories can be built both by cave lions and entertainers. Paleolithic marsupials can be built by both procoptodons and entertainers.
=> irishhombre mod mod.

Assets/XML/Units/CIV4UnitInfos.xml, Assets/XML/Units/CulturalUnits_CIV4UnitInfos.xml, Sources/CvPlot.cpp, Sources/CvUnit.cpp
Also added change for hunters to target armed guard units first, following discord discussion.
Linked issue: Resolves #238 
(Also possibly #286 but haven't confirmed)
=> Taunt chance no longer takes priority over strength when evaluating 'best defender' in 'target first' combat

Sources/CvCityAI.cpp, Sources/CvUnitAI.cpp
Towers (but not forts) should not be considered to be built in the workable radius of a city by AI workers. Won't know for sure until a longer test is done, though.
Not sure if there is a scenario for which a tower in workable radius is desirable, but not fort. An extreme edge case may be a 2-tile wide chokepoint, but that'd be hard to check for lol. Visibility range boons may as well be given to units in a city rather than near it.
=> Tower spam reduction in city radius

Sources/CvDLLWidgetData.cpp, Sources/CvPlayer.cpp, Sources/CvPlayer.h
https://github.com/caveman2cosmos/Caveman2Cosmos/issues/312
fix #312
Just needed a count of outstanding free techs to select.
The thing breaking it looks like some very old code to stop people selecting the free tech over and over.
=> fix(Tech): getting more than one free tech in a single turn now works

Sources/CvGameTextMgr.cpp
=> Fix crash (end turn when making text for newly researched buildings?)

.github/workflows/commit.yml
Since commit `988d258110af5268cc2f66047f8c1e1262f8ad44` commit tests are
now run when pushed inside the repo, but PRs from forked repos does not
trigger a run. This is problematic when accepting PRs from outside the
repo, potential errors will only be discovered after merging, which is
bad.
By adding the trigger `pull_request`, all PRs to any branches in the
repo, will trigger a Github Actions run.
=> CI: Enable commit tests to be run on PRs

.github/workflows/commit.yml, Tools/Lint/setup.sh
There have been a recent update to the `get-pip.py` script for
installing `pip` for python 2.7. This updated causes installing pip to
fail with the following error message:
```
Traceback (most recent call last):
File "get-pip.py", line 24226, in <module>
main()
File "get-pip.py", line 199, in main
bootstrap(tmpdir=tmpdir)
File "get-pip.py", line 82, in bootstrap
from pip._internal.cli.main import main as pip_entry_point
File "/tmp/tmpG8aJb5/pip.zip/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax
```
This commit downgrades the Ubuntu version from 20.04 to 18.04 to avoid
using this script. Ubuntu 18.04 can install pip from the default repo,
avoiding `get-pip.py` entirely.
Another benefit is that it simplifies the setup script as well.
=> CI: Downgrade to Ubuntu 18.04 to avoid get-pip

.github/workflows/commit.yml
Since knowing that all XMLs are valid is critical for a successful
build, all of the XMLs in the repo are now checked on each push/PR to
the repo from the outside.
Hopefully this will make it easier for external contributors to know
that their XMLs are valid before a potential merge. The reason for this
is that although the validator is currently run in `Appveyor` today, it
is not easy to replicate the setup for getting `Appveyor` to run on a
forked repo. With `Github Actions`, all of this is handled for the user.
One drawback with this approach is that with this commit merged the
validation is run twice. But the benefit of reducing the chance of
breaking master should outweigh this drawback.
=> CI: Run XMLValidator in Github Actions

Sources/CvInfos.h, Sources/CvPlayer.cpp, Sources/CvUnit.cpp, Sources/CvUnit.h, Sources/CvUnitInfo.cpp
Matt: this loop
// Toffer - ToDo
//	- Should limit loop to only UnitInfo builds and the extra builds for this unit.
//	- Both are vectors and are both referenced in the CvUnit::hasBuild() function.
Matt: switched this to a boost function, but it's probly not much faster.
// Toffer - This can't be faster than just doing an erase of the element with the build id; can it?
=> switched a loop for unit build types to foreach_

Caveman2Cosmos.ini, Sources/CvGlobals.cpp, Sources/OutputRatios.cpp, Sources/OutputRatios.h
You can use the OutputRatios constructor with no parameters to start with defaults.
Feel free to change or delete this stuff.
The ini file probably needs some comments.
=> added default AI yield weight values to c2c ini file

Sources/CvCity.cpp, Sources/CvGlobals.h
=> culture level option fix

Assets/XML/A_New_Dawn_GlobalDefines.xml, Assets/XML/GameText/Global_CIV4GameText.xml, Assets/XML/Technologies/CIV4TechInfos.xml, Assets/XML/Terrain/CIV4FeatureInfos.xml, Assets/XML/Terrain/CIV4ImprovementInfos.xml, Assets/XML/Terrain/CIV4TerrainInfos.xml, Sources/CvCity.cpp, Sources/CvCityAI.cpp, Sources/CvDLLWidgetData.cpp, Sources/CvGameTextMgr.cpp, Sources/CvPlayerAI.cpp, Sources/CvPlot.cpp, Sources/CvPlot.h, Sources/CvUnitAI.cpp
Has an issue where other civs will display tiles as not being influenced by cities when they are in fact.
This is caused by the cache clearing between player turn and AI turn; same cause for the 'culture last turn' vs 'this turn' cache. Should be fixed before accepting; whether to only show for player's own culture or by making new cache, or changing where cache clears, not certain. Thoughts Toffer?
=> City culture plot cache

Assets/Python/EntryPoints/CvRandomEventInterface.py, Assets/XML/Events/CIV4EventInfos.xml, Assets/XML/Events/CIV4EventTriggerInfos.xml, Assets/XML/GameText/Events_CIV4GameText.xml
-Event trigger spicy gives spice resource, decreased chance of event happening, event can happen more than 1 time, added bonus text, increased event choice gold cost, adjusted AI-weight decision values
-Event baby boom gives food, decreased chance of event happening, event has one more option to chose now(gold for food), event gives more food, adjusted AI-weight decision values
-Event bard tales gives culture, decreased chance of event happening, event can happen more than 1 time, increased cost and rewards from the event, adjusted AI-weight decision values
-Event looters where if enemy city has unrest there is an option to destroy improvements, decreased chance of event happening, made every event do more damage, event choice cost more
-Event brothers in need where you give a nation of …
=> Updated events:

Assets/XML/Terrain/CIV4ImprovementInfos.xml, Assets/XML/Units/CIV4BuildInfos.xml
the wood gatherer improvement is currently unlocked at TECH_WOODWORKING and its replacement is at carpentry that you can research as soon as you complete woodworking. This pull moves the the wood gatherer to simple wood working about 16 techs before carpentry.
=> Moved wood gatherer to simple wood working

Assets/Modules/P2K_Multimaps_Test/MM_CIV4UnitInfos.xml, Sources/CvMap.cpp, Sources/CvMap.h, Sources/CyMap.cpp, Sources/CyMap.h
Not sure how easy it is to be able to instantly TP a unit between multimaps, as trying to do a `switchMap` during `doOutcome` (regardless of if the switch was in the XML/Python or in actual C++) would crash the game. However to properly create a unit on Earth or get the capital's coords, the current map does need to be Earth... too much random stuff everywhere just assumes to use GC.getMap instead of being passed a map to operate on
=> Fix moving units from Earth to Cislunar placing them in non-Orbit plots; Fix space unit mission rewards not moving to capital properly

Assets/XML/Units/U_Sea_CIV4UnitInfos.xml
The Paddle Steamer is a steam-powered ship. Let it ignore Terrain movement costs. Otherwise it's slower than any wooden ship with the Maneuvering 1 promotion.
=> Paddle Steamer Movement Fix

Assets/Modules/Cultures/Cultures_Cultural_CIV4UnitInfos.xml, Assets/XML/Units/U_Land_CIV4UnitInfos.xml
Parity changes for Tigurini Scouts and Wapiti, giving them the same abilities as the explorer, and for Unmanned trike, giving it the same abilities as the motorcycle. No stat changes.
=> Recon unit parity fix

Assets/XML/GameText/CIV4GameTextInfos_GreatPeople.xml
This was rather incoherent; rewrote it based largely on https://iranicaonline.org/articles/azod-al-dawla-abu-soja which appears to be the source for the equivalent mangled text on Wikipedia.
=> Rewrite description for Azod od-Dowleh

.vscode/c_cpp_properties.json, .vscode/extensions.json, Sources/.vscode/c_cpp_properties.json, Sources/CvCityAI.cpp, Sources/CvPlayerAI.cpp, Sources/CvTalkingHeadMessage.cpp
this PR does some tweaks to improve the support of vscode intellisense.
important, as of current, you need to use version  `1.19.4`
`1.19.5` and onwards currently breaks intellisense in this project read: 
https://github.com/microsoft/vscode-cpptools/issues/12451
=> Improve support for vscode intellisense

Assets/XML/GameText/BuildingHelp_CIV4GameText.xml, Assets/XML/Units/CIV4SpawnInfos.xml, Assets/XML/Units/U_Animals_CIV4UnitInfos.xml
-Updated hunting unit reward xp according to unit size might and aggression (small and weaker animals give less, bigger give more)
-Updated unit strength to better match their size might and aggression
-Reduced subdue chance on animal kill for all animals to 5% from 10% in order to buff hunter hunting and reduce unit hunting
-Added some animals missing subdue chance
-Updated animal food reward according to the size of the animal and the quality of meat
-Updated animal hammer reward according to the size of the animal and the quantity of bone and other construction usable materials
-Add animal commercial value according to its commercially viable parts(hide, tusks, oil, feathers etc...)
=> Hunting rewards update

Assets/XML/GameText/Global_CIV4GameText.xml, Assets/XML/GameText/Mission_CIV4GameText.xml
Specific request to undo a previous typo fix for inflaton field, its an actual word not a mispelling of inflation. Done.
Tooltip for start golden age was confusing people so edited the text there as well to eliminate ambiguity.
=> Requested typo fix and tooltip fix

Sources/CvCityAI.cpp, Sources/CvPlayer.cpp, Sources/CvPlayerAI.cpp, Sources/CvSelectionGroupAI.cpp, Sources/CvUnit.cpp, Sources/CvUnitAI.cpp
**AI Tweaks to patch prec. update**
- Add the production of Collateral Units for Main Attack Stack (Tag 32)
- Extend the MergeRange of Collateral Units and Attack City Stacks
- Change Level of some less used logs
- Give more Strength goals to Warmonger, and less for peacefull Leaders
**AI near behavior fix (when 1 tile near)**
- Fix a bug when stack is choosing again the target city, and at 1 tile from a city (pathing fail)
- When 2 stacks are at 1 tile, the first move, and send skip to the other (try to avoid ping-pong place exchange)
- Dont' Train Attack units if turtle strategy
- Add Logs for GroupList - Potentiel global failure that give Endless loop
- Add Logs for Bombard and Ratio calculation in Attack
- Avoid long range Hunt for hunters (they will move one by one, to eventually …
=> AI Attack City Patch - Merge Range and Collaterals - with Endlessloop fix

Assets/XML/Units/U_Land_CIV4UnitInfos.xml, Assets/XML/Units/U_Neanderthals_CIV4UnitInfos.xml
The riding school no longer boost all mounted animals. Clay pits cant be build everywhere when you have fine clay. The cost of elephants has been increased
=> This commit makes elephants more expensive to match their power.

Assets/XML/GameText/Units_CIV4GameText.xml, Assets/XML/Units/CIV4UnitInfos.xml, Sources/CvCityAI.cpp, Sources/CvUnitAI.cpp
- Limit set to 6 => ~30, depending on Map Size.
Small fixes :
- Set ICBM as suicidal (otherwise, cause a endless loop)
- Add Text for DebugLite (to have Role/Mission of AI during Tests)
=> Set a Sea Workers needed Global Limit (to avoid IA Spamming)

Assets/Python/Revolution/Gameready/AIAutoPlay.py, Assets/XML/Buildings/GreatWonders_CIV4BuildingInfos.xml, Assets/XML/Buildings/NationalWonders_CIV4BuildingInfos.xml, Assets/XML/GameText/Global_CIV4GameText.xml, Assets/XML/GameText/Hints_CIV4GameText.xml, Assets/XML/GameText/Promotions_CIV4GameText.xml, Assets/XML/Terrain/Manufactured_CIV4BonusInfos.xml, Sources/CvCity.cpp, Sources/CvCityAI.cpp, Sources/CvGame.cpp, Sources/CvGameCoreDLL.cpp, Sources/CvGameCoreDLL.h, Sources/CvGameCoreUtils.cpp, Sources/CvGameCoreUtils.h, Sources/CvGameTextMgr.cpp, Sources/CvMap.cpp, Sources/CvMap.h, Sources/CvMapInterfaceBase.h, Sources/CvPathGenerator.cpp, Sources/CvPlayer.cpp, Sources/CvPlot.cpp, Sources/CvPlot.h, Sources/CvSelectionGroup.cpp, Sources/CvTeam.cpp, Sources/CvTeamAI.cpp, Sources/CvTeamAI.h, Sources/CvUnitAI.cpp, Sources/CvViewport.cpp, Sources/CvViewport.h
[FogWar Decay Modmod + small fixes](https://github.com/Calvitix/Caveman2Cosmos/commit/650d4644d3646174d1c4ed51772e92bc72d00eb0)
- Add the FogWar Decay modmod, activated via define ENABLE_FOGWAR_DECAY
- Add a AutomateType to Description in GameCoreUtils - to show it in Hover infos
- Several fixes / addition in French text XML
- Change Central Administration to need 30 -> 15, and Capital -> 20
CTD fixes & some Refactoring
- Prevent CTD when profiling in IFPEndSample()
- Prevent CTD when iEnemyOffence = 0 in CvUnitAI::AI_attackCityMove() when unit next to target city
- Prevent CTD in log message in CvUnitAI::processContract()
- Refactor Cvcity methods : hasRawVicinityBonus and calculateCultureDistance  (that have been spotted via profiling)
- Refactor CvCityAI::AI_addBestCitizen, and …
=> FogWar Decay Modmod + small XMLS fixes + CTD fixes & some Refactoring

Assets/XML/GameText/Global_CIV4GameText.xml, Sources/C2C (VS2019).vcxproj, Sources/C2C (VS2019).vcxproj.filters, Sources/CvArmy.cpp, Sources/CvArmy.h, Sources/CvDefines.h, Sources/CvEnums.h, Sources/CvGame.cpp, Sources/CvPlayer.cpp, Sources/CvPlayer.h, Sources/CvPlayerAI.cpp, Sources/CvPlayerAI.h, Sources/CvSelectionGroup.cpp, Sources/CvSelectionGroup.h, Sources/CvUnitAI.cpp
Experimental Army Concept : 
- An army is created when a stack reach at least 6 members. It will try to enroll all others Attack and Attack City stacks in the Area, and all the idle units that can reach the Army's Leader. They will have all the same target.
- If a Unit belong to an army, the targetplot is automatically the target of the army
- It handles when Army leader is killed, when the forces are not enough, the army is disbanded.
- Add the need of a healer in a Attack_City Stack = will provide Job offer in broker to have one.
- an Attack_City Stak will need at least 2 Capture City units (hired via broker)
- If the stack ends in a city, eject a defender in that city.
- Add ArmyID in SelectionGroup
- Add in PlayerAI the Ability to form armies, and a specifid Do_turn() before the units …
=> AI Army Experimental Branch
